import { useEffect, useState } from 'react';
import { request } from './api';
type Run = { status: string; error: string | null; result: { explanation: string; tool: string; finding_id: string; interpretation: string } | null };
export function SecurityAgent({ projectId }: { projectId: string }) {
  const [question, setQuestion] = useState('Покажи самые важные проблемы безопасности.'); const [allowed, setAllowed] = useState(false); const [busy, setBusy] = useState(false); const [run, setRun] = useState<Run | null>(null); const [error, setError] = useState('');
  useEffect(() => { let live = true; let timer: number; const poll = async () => { try { const data = await request<Run | null>(`/api/projects/${projectId}/agent`); if (live) setRun(data); } catch (e) { if (live) setError(e instanceof Error ? e.message : 'Ошибка'); } if (live) timer = window.setTimeout(poll, 5000); }; void poll(); return () => { live = false; clearTimeout(timer); }; }, [projectId]);
  async function ask(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await request(`/api/projects/${projectId}/agent`, { method: 'POST', body: JSON.stringify({ question, allow_actions: allowed }) }); setRun({ status: 'PENDING', result: null, error: null }); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка'); } finally { setBusy(false); } }
  return <section className="panel"><div className="panel-heading"><div><h2>AI Security Agent</h2><p>Вопрос о находках этого проекта · модель на Bult.ai</p></div></div><form onSubmit={ask}><label>Ваш вопрос<textarea value={question} onChange={e => setQuestion(e.target.value)} maxLength={1000} minLength={5} required /></label><label className="fix-consent"><input type="checkbox" checked={allowed} onChange={e => setAllowed(e.target.checked)} />Разрешить запуск проверок и подготовку предложений исправлений. Применение — после отдельного просмотра.</label><button className="button primary" disabled={busy || ['PENDING', 'RUNNING'].includes(run?.status || '')}>Отправить</button></form>{error && <p role="alert">{error}</p>}{run && <div className="ai-content"><p>{run.status === 'PENDING' ? 'В очереди' : run.status === 'RUNNING' ? 'Агент получает данные…' : run.status === 'FAILED' ? run.error : ''}</p>{run.result && <><p>{run.result.explanation}</p><small>Инструмент: {run.result.tool} · {run.result.interpretation}</small>{run.result.finding_id && <p><a href={`#/findings/${run.result.finding_id}`}>Scanner evidence →</a></p>}</>}</div>}</section>;
}
