"""Stage 2 foundation schema

Revision ID: 0001
Revises:
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "projects",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("owner_id", "name", name=op.f("uq_projects_owner_id_name")),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("default_branch", sa.String(length=200), server_default="main", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_repositories_project_id_projects"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_repositories_project_id_id")),
        sa.UniqueConstraint("project_id", "url", name=op.f("uq_repositories_project_id_url")),
    )
    op.create_index(op.f("ix_repositories_project_id"), "repositories", ["project_id"], unique=False)
    op.create_table(
        "scans",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "CLONING",
                "SCANNING",
                "NORMALIZING",
                "AI_ANALYSIS",
                "COMPLETED",
                "FAILED",
                name="scan_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("target_url", sa.String(length=2048), nullable=True),
        sa.Column("scanner_config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("scanner_results", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "repository_id"],
            ["repositories.project_id", "repositories.id"],
            name=op.f("fk_scans_project_id_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_scans_project_id_id")),
    )
    op.create_index(op.f("ix_scans_project_id"), "scans", ["project_id"], unique=False)
    op.create_index(op.f("ix_scans_status"), "scans", ["status"], unique=False)
    op.create_table(
        "findings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("scanner", sa.Enum("gitleaks", "semgrep", "trivy", "nuclei", name="scanner", native_enum=False, create_constraint=True), nullable=False),
        sa.Column(
            "category",
            sa.Enum("secret", "code", "dependency", "configuration", "web", name="category", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "UNKNOWN", name="severity", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("original_severity", sa.String(length=50), nullable=True),
        sa.Column("file", sa.String(length=2048), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("rule_id", sa.String(length=300), nullable=False),
        sa.Column("cwe", sa.String(length=64), nullable=True),
        sa.Column("cve", sa.String(length=64), nullable=True),
        sa.Column("evidence", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "AI_ANALYZED",
                "FIX_PROPOSED",
                "FIX_APPLIED",
                "RECHECKING",
                "VERIFIED_FIXED",
                "STILL_DETECTED",
                name="finding_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("line_end IS NULL OR (line_start IS NOT NULL AND line_end >= line_start)", name=op.f("ck_findings_line_range")),
        sa.CheckConstraint("line_start IS NULL OR line_start > 0", name=op.f("ck_findings_positive_line")),
        sa.ForeignKeyConstraint(
            ["project_id", "scan_id"], ["scans.project_id", "scans.id"], name=op.f("fk_findings_project_id_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_findings_project_id_id")),
        sa.UniqueConstraint("scan_id", "scanner", "fingerprint", name=op.f("uq_findings_scan_id_scanner_fingerprint")),
    )
    op.create_index(op.f("ix_findings_fingerprint"), "findings", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_findings_project_id"), "findings", ["project_id"], unique=False)
    op.create_index(op.f("ix_findings_scan_id"), "findings", ["scan_id"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_table(
        "scan_jobs",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="job_status", native_enum=False, create_constraint=True),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], name=op.f("fk_scan_jobs_scan_id_scans"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_jobs")),
        sa.UniqueConstraint("scan_id", name=op.f("uq_scan_jobs_scan_id")),
    )
    op.create_index(op.f("ix_scan_jobs_status"), "scan_jobs", ["status"], unique=False)
    op.create_table(
        "ai_analyses",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", name="analysis_status", native_enum=False, create_constraint=True),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("recommended_fix", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], name=op.f("fk_ai_analyses_finding_id_findings"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analyses")),
        sa.UniqueConstraint("finding_id", "id", name=op.f("uq_ai_analyses_finding_id_id")),
    )
    op.create_index(op.f("ix_ai_analyses_finding_id"), "ai_analyses", ["finding_id"], unique=False)
    op.create_table(
        "rescans",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("original_scan_id", sa.Uuid(), nullable=False),
        sa.Column("verification_scan_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("VERIFIED_FIXED", "STILL_DETECTED", "INCONCLUSIVE", name="rescan_outcome", native_enum=False, create_constraint=True),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("original_scan_id <> verification_scan_id", name=op.f("ck_rescans_different_scans")),
        sa.ForeignKeyConstraint(
            ["project_id", "finding_id"], ["findings.project_id", "findings.id"], name=op.f("fk_rescans_project_id_finding_id_findings"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "original_scan_id"], ["scans.project_id", "scans.id"], name=op.f("fk_rescans_project_id_original_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "verification_scan_id"],
            ["scans.project_id", "scans.id"],
            name=op.f("fk_rescans_project_id_verification_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rescans")),
    )
    op.create_index(op.f("ix_rescans_project_id"), "rescans", ["project_id"], unique=False)
    op.create_table(
        "fixes",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("diff", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("PROPOSED", "APPLIED", name="fix_status", native_enum=False, create_constraint=True), server_default="PROPOSED", nullable=False
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id", "analysis_id"], ["ai_analyses.finding_id", "ai_analyses.id"], name=op.f("fk_fixes_finding_id_analysis_id_ai_analyses")
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], name=op.f("fk_fixes_finding_id_findings"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixes")),
    )
    op.create_index(op.f("ix_fixes_finding_id"), "fixes", ["finding_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fixes_finding_id"), table_name="fixes")
    op.drop_table("fixes")
    op.drop_index(op.f("ix_rescans_project_id"), table_name="rescans")
    op.drop_table("rescans")
    op.drop_index(op.f("ix_ai_analyses_finding_id"), table_name="ai_analyses")
    op.drop_table("ai_analyses")
    op.drop_index(op.f("ix_scan_jobs_status"), table_name="scan_jobs")
    op.drop_table("scan_jobs")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_scan_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_project_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_fingerprint"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_scans_status"), table_name="scans")
    op.drop_index(op.f("ix_scans_project_id"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_repositories_project_id"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###
